version: "3.8"
services:
  user-service:
    build: ./backend/user-service
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  product-service:
    build: ./backend/product-service
    ports:
      - "8082:8080"
    depends_on:
      - redis

  cart-service:
    build: ./backend/cart-service
    ports:
      - "8083:8080"
    depends_on:
      - dynamodb

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
