root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/user-service"
  cmd = "go build -o ./tmp/user-service ./cmd/main.go"
  include_ext = ["go"]
  exclude_dir = ["migrations", "tmp", "vendor", "email-worker"]
  delay = 1000
  stop_on_error = true

[log]
  time = true
  color = true

[misc]
  clean_on_exit = true