root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/email-worker"
  cmd = "go build -o ./tmp/email-worker ./email-worker/email_worker.go"
  include_ext = ["go"]
  exclude_dir = ["migrations", "tmp", "vendor", "cmd"]
  delay = 1000
  stop_on_error = true

[log]
   time = true
   color = true

[misc]
   clean_on_exit = true