apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-worker
  template:
    metadata:
      labels:
        app: email-worker
    spec:
      containers:
        - name: email-worker
          image: email-worker:latest
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
            - name: SMTP_SERVER
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: email-worker
spec:
  selector:
    app: email-worker
  ports:
    - port: 5672
      targetPort: 5672