apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/kong.yml
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
          ports:
            - containerPort: 8000
            - containerPort: 8001
          volumeMounts:
            - name: kong-config
              mountPath: /kong/kong.yml
              subPath: kong.yml
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: user-service
        url: http://user-service:8080
        routes:
          - name: user-service-route
            paths:
              - /api/users
            strip_path: true
---
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: admin
      port: 8001
      targetPort: 8001
  selector:
    app: kong
  type: LoadBalancer