apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: postgres://user:pass@postgres:5432/shopnest?sslmode=disable
            - name: REDIS_ADDR
              value: redis:6379
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
            - name: SMTP_SERVER
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-service